### ISSUE TITLE
Refactor `multiplication.c` to Reduce Duplication and Free Memory

### ISSUE THREAD

**Issue by arya2004** [arya2004/Calculator#6]
The `multiplication.c` file contains several code blocks that could benefit from refactoring to remove duplication. Identify the redundant code and create functions to streamline the logic. Also, make sure to free any dynamically allocated memory at the end of the multiplication operation.

**Acceptance Criteria**:
- Minimize code duplication by using helper functions.
- Free all dynamically allocated memory at the end of the operation.
- Ensure the correctness of the program after refactoring by running tests.

**Comment by VaradJadhav** [comment]
Hey @arya2004 can you assign me this?

**Comment by VaradJadhav** [comment]
Hey @arya2004 i want to work on this issue. Can you assign me?

**Comment by arya2004** [comment]
sure @VaradJadhav
