### ISSUE TITLE
Refactor `factorial.c` to Improve Code Reusability and Free Memory

### ISSUE THREAD

**Issue by arya2004** [arya2004/Calculator#8]
The `factorial.c` file contains repetitive logic that can be optimized by refactoring the code into reusable functions. This will reduce the overall code size and improve maintainability. Additionally, ensure that any dynamically allocated memory is properly freed at the end of the factorial operation to prevent memory leaks.

**Acceptance Criteria**:
- Refactor repeated logic into reusable functions.
- Free any dynamically allocated memory at the end of the operation.
- Ensure all existing unit tests pass post-refactor.

**Comment by Veerhan-glitch** [comment]
Can you assign this to me
